# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"

env:
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.2

cache:
  directories:
    - $HOME/.pip-cache/

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies
install:
  - pip install Django==$DJANGO_VERSION --download-cache $HOME/.pip-cache
  - if [[ $DJANGO_VERSION == '1.5.5' ]]; then pip install django-discover-runner --download-cache $HOME/.pip-cache; fi
  - pip install -q -r requirements/requirements-test.txt --download-cache $HOME/.pip-cache

# command to run tests using coverage
script:
  - coverage run --source nowait --omit=nowait/migrations/*,nowait/tests/factories.py project_template/manage.py test nowait
  - make test-ft

# report coverage to coveralls.io
after_success: coveralls
